### PR TITLE
Improve Google search metadata

### PR DESCRIPTION
**Pull request by brendanlong**
This adds several hints for Google to index our site and show better search results:

 - sitemap.xml helps Google know which pages it should index, and gives us the ability to change the internal ranking of pages if we want to (currently I set them all equal).
 - microdata improves what Google will show in search results

### CODE REVIEW

**Comment by brendanlong** [comment]
Google says the microdata I added is all valid:

screenshot from 2018-01-28 12-35-45

**Comment by brendanlong** [comment]
We could also add foundingDate and founder if we wanted to, but I'm not sure what info to put. Out about page says we were officially founded in 2015 but it doesn't have the full date, and I don't know what stuff we should link to if we put Mike's info here.

**Comment by mfinnarena** [comment]
Thanks Brendan. I like this idea and happy to provide any more information. I don't think we need to add Mike's info as founder though.

I'll leave it to Kevin to review the changes.

**Comment by kevinqiu** [comment]
@mfinnarena You may need to run `pip install -r requirements.txt` again before you are able to make updates to the site since this adds a new external module(`gitpython`). Alternatively, `pip install gitpython` should work as well.

**Pull request merged**
