### PR TITLE
Change Bonnie's title from 'Vice President of Data Science' to 'Vice …

### PR DESCRIPTION
**Pull request by alysedunn**
…President of Analytics Innovation'

### CODE REVIEW

**Comment by alysedunn** [comment]
@kevinqiu : When you get a chance, could you please:
- Review this (it is a very small change)
- Give me your thoughts on whether or not you think it's worth the overhead to do any kind of versioning with this stuff. We can of course version in Git/Github, and I just realized that you can also version your objects in S3. I think we should skip the versioning until we feel like we need it given how small a project this is (right now), but I'm open to your thoughts.

Thanks!
A

**Comment by kevinqiu** [comment]
What do you mean by versioning? Like tagging the commits with versions?

**Comment by kevinqiu** [comment]
Also, approved!

**Comment by alysedunn** [comment]
@kevinqiu : K; I'm going to go ahead and merge this to master.

Also, to clarify what I meant by versioning: I actually meant creating releases and versioning the releases by (see https://github.com/arenadotio/corporate_site/releases). I'm not going to go through that right now, but maybe something to talk about sometime after we both get back.

**Pull request merged**
